stages:
  - test
  - package
  - publish

test: &test
  stage: test
  image: $CI_REGISTRY/docker-images/layers:jessie-ruby
  script:
    - apt-get install attr ruby-ffi
    - make test

package: &package
  image: $CI_REGISTRY/docker-images/layers:$DISTRO-deb
  variables:
    DISTRO: jessie
  stage: package
  script:
    - package
  artifacts:
    paths:
      - pkg/

publish:
  stage: publish
  variables:
    RSYNC_HOSTNAME: repo.bytemark.co.uk
  tags:
    - shell
  script:
    - publish


