stages:
  - test
  - package
  - publish

test: &test
  stage: test
  image: $CI_REGISTRY/docker-images/layers:jessie-ruby
  script:
    - apt-get install attr ruby-ffi
    - make test

.package: &package
  image: $CI_REGISTRY/docker-images/layers:$DISTRO-deb
  stage: package
  script:
    - package
  artifacts:
    paths:
      - pkg/

package:wheezy:
  <<: *package
  variables:
    DISTRO: wheezy

package:jessie:
  <<: *package
  variables:
    DISTRO: jessie

package:stretch:
  <<: *package
  variables:
    DISTRO: stretch

package:precise:
  <<: *package
  variables:
    DISTRO: precise

package:trusty:
  <<: *package
  variables:
    DISTRO: trusty

package:xenial:
  <<: *package
  variables:
    DISTRO: xenial


publish:
  stage: publish
  variables:
    RSYNC_HOSTNAME: repo.bytemark.co.uk
  tags:
    - shell
  script:
    - publish
  dependencies:
    - package:wheezy
    - package:jessie
    - package:stretch
    - package:precise
    - package:trusty
    - package:xenial
